import {VERSION,stepProgress,fields,blank,visible,answered,label,validate,normalize,recommend,brief} from './model.mjs';
const $=s=>document.querySelector(s),key='kickoff.projects.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>globalThis.crypto?.randomUUID?.()||`p-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const titles=['产品定位','业务与功能','专项设置','约束与偏好','项目简报'];
let projects=[],current,step=0,errors=[],storageError=false,toastTimer;
const generated=new Map(); let generating=false;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500)}
function validProject(p){if(!p||typeof p.id!=='string'||p.id.length>150)throw Error('无效标识');return {id:p.id,updated:typeof p.updated==='string'&&Number.isFinite(Date.parse(p.updated))?p.updated:new Date().toISOString(),data:normalize(p.data),agents:p.agents&&typeof p.agents.markdown==='string'&&p.agents.markdown.length<=40000&&typeof p.agents.input==='string'&&p.agents.input.length<=40000?p.agents:null}}
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){if(saved.version!==VERSION||!Array.isArray(saved.projects))throw Error('不支持的版本');projects=saved.projects.map(validProject);current=projects.find(p=>p.id===saved.currentId)||projects[0]}}catch{storageError=true;toast('无法读取本机草稿；原数据未覆盖，请导出备份。')}
if(!current){current={id:uid(),updated:new Date().toISOString(),data:blank()};projects.push(current)}
for(const p of projects)if(p.agents)generated.set(p.id,p.agents);
function persist(){current.updated=new Date().toISOString();if(storageError){$('#saveStatus').textContent='保存不可用 · 请导出';return}try{localStorage.setItem(key,JSON.stringify({version:VERSION,currentId:current.id,projects}));$('#saveStatus').textContent='已保存到本机'}catch{storageError=true;$('#saveStatus').textContent='保存失败 · 请导出';toast('存储不可用，请导出 JSON 保存本次填写。')}}
function fieldHTML(f){const v=current.data[f.id],err=errors.find(e=>e.id===f.id);const title=`${esc(f.label)}<span class="badge ${f.required?'required':''}">${f.required?'必填':'选填'}</span>${f.kind==='multi'?'<span class="field-multi">多选</span>':''}`;let content='';
 if(f.kind==='text'||f.kind==='textarea'){const attrs=`id="field-${f.id}" data-field="${f.id}" class="text-input" maxlength="${f.max||5000}" placeholder="${esc(f.placeholder||'')}" ${f.required?'required aria-required="true"':''} ${err?`aria-invalid="true" aria-describedby="error-${f.id}"`:''}`;content=`<label class="field-title" for="field-${f.id}">${title}</label>${f.kind==='textarea'?`<textarea ${attrs}>${esc(v)}</textarea>`:`<input type="text" ${attrs} value="${esc(v)}">`}`}
 else content=`<legend>${title}</legend><div class="${f.cards?'choice-grid':'chips'}">${f.options.map(o=>{const selected=Array.isArray(v)?v.includes(o.value):v===o.value;return `<button type="button" class="${f.cards?'choice':'chip'} ${f.kind==='single'?'radio':''} ${selected?'selected':''}" data-choice="${f.id}" data-value="${o.value}" aria-pressed="${selected}">${f.cards?`<span class="choice-mark" aria-hidden="true">✓</span><span class="choice-text"><strong>${esc(o.label)}</strong>${o.description?`<small>${esc(o.description)}</small>`:''}</span>`:esc(o.label)}</button>`}).join('')}</div>`;
 return `<fieldset class="field ${err?'has-error':''}" data-group="${f.id}">${content}${err?`<div id="error-${f.id}" class="field-error" role="alert">${esc(err.message)}</div>`:''}</fieldset>`;
}
function renderSteps(){$('#steps').innerHTML=titles.map((t,i)=>{const p=stepProgress(current.data,i);return `<button class="step ${step===i?'active':''}" data-step="${i}" ${step===i?'aria-current="step"':''}><span class="number">${i+1}</span><span class="step-label">${t}</span>${i<4?`<small aria-label="已填 ${p.filled} 项，共 ${p.total} 项" title="已填 / 当前可见字段">${p.filled}/${p.total}</small>`:''}</button>`}).join('')}

function render(){renderSteps();$('#formView').hidden=step===4;$('#resultView').hidden=step!==4;if(step===4){renderResult();return}const fs=fields.filter(f=>f.step===step&&visible(f,current.data));$('#formView').innerHTML=`<div class="page-heading"><h1>${titles[step]}</h1>${step?'<span class="muted">选填</span>':''}</div><div class="form-card">${fs.map(fieldHTML).join('')}</div><div class="form-footer"><span class="footer-meta">${step+1} / 4 · ${stepProgress(current.data,step).filled}/${fs.length} 已填</span><div class="footer-actions">${step?'<button class="btn" data-prev>上一步</button>':''}${step<3?'<button class="btn" data-result>生成简报</button>':''}<button class="btn primary" data-next>${step===3?'生成简报':step>0?'下一步 / 跳过':'下一步'}</button></div></div>`}
const list=a=>`<ul>${a.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
function renderResult(){const d=current.data,p=recommend(d),active=fields.filter(f=>visible(f,d)&&answered(d[f.id]));$('#resultView').innerHTML=`<h1>${esc(d.name.trim()||'项目简报')}</h1><div class="toolbar"><button class="btn primary" id="copyBrief">复制简报</button><button class="btn" id="exportMd">导出 Markdown</button><button class="btn" id="exportJson">备份 JSON</button><button class="btn" data-step="0">编辑</button></div><section class="result-card"><div class="toolbar"><button class="btn primary" id="generateAgents" ${generating?'disabled':''}>${generating?'生成中…':'生成 AGENTS.md'}</button><button class="btn" id="downloadAgents" ${generated.get(current.id)?'':'hidden'}>下载 AGENTS.md</button></div><p class="muted" id="agentsStatus" role="status">${generating?'正在调用本机 Codex':'使用本机 Codex · 生成项目约束与验收标准'}</p><textarea class="text-input brief-text" id="agentsText" aria-label="AGENTS.md 草案" ${generated.get(current.id)?'':'hidden'}>${esc(generated.get(current.id)?.markdown||'')}</textarea></section><div class="result-banner"><span class="pill">建议</span><h2 style="margin-top:12px">${esc(p.mode)}</h2><p>${esc(p.first)}</p></div><div class="result-grid"><section class="result-card"><h3>你的参与</h3>${list(p.you)}<p style="margin:14px 0 0">${esc(p.participation)}</p></section><section class="result-card"><h3>助手负责</h3>${list(p.agent)}<p style="margin:14px 0 0">${esc(p.priority)}</p></section></div><section class="result-card"><h3>已填写 <span class="badge">${active.length} 项</span></h3><dl class="summary-list">${active.map(f=>`<div class="summary-row"><dt><button class="summary-edit" data-edit-field="${f.id}" data-edit-step="${f.step}" title="修改${esc(f.label)}">${esc(f.label)} <span aria-hidden="true">↗</span></button></dt><dd>${esc(label(f.id,d[f.id]))}</dd></div>`).join('')}</dl></section><section class="result-card"><h3>架构判断方向</h3>${list(p.architecture.length?p.architecture:['先结合目标确认业务关系、数据和运行边界。'])}</section><section class="result-card"><h3>验证重点</h3>${list(p.checks)}</section><section class="result-card"><h3>开发前待确认 <span class="badge">${p.pending.length} 项</span></h3>${list(p.pending.length?p.pending:['暂无额外项，需结合实际业务核对。'])}</section><details class="result-card"><summary>完整简报</summary><textarea class="text-input brief-text" id="briefText" aria-label="完整项目简报" readonly>${esc(brief(d))}</textarea></details><p class="muted">复制或导出后发给开发会话。生成 AGENTS.md 时会将简报发送给本机 Codex 使用的模型。</p>`}
function navigate(next){if(next===4||(step===0&&next===1)){errors=validate(current.data);if(errors.length){step=0;render();const el=$(`[data-group="${errors[0].id}"]`);el?.scrollIntoView({block:'center'});el?.querySelector('input,textarea,button')?.focus({preventScroll:true});return}}errors=[];step=next;render();$('#main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
function download(content,ext,mime){const name=(current.data.name.trim()||'项目简报').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'-').slice(0,80),url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=`${name}.${ext}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function exportJSON(){download(JSON.stringify({app:'project-kickoff',version:VERSION,exportedAt:new Date().toISOString(),project:current},null,2),'json','application/json;charset=utf-8')}
async function copy(){try{await navigator.clipboard.writeText(brief(current.data));toast('已复制')}catch{const t=$('#briefText');t.closest('details').open=true;t.focus();t.select();toast('请使用复制快捷键，或导出 Markdown')}}
function showDrafts(){const sorted=[...projects].sort((a,b)=>b.updated.localeCompare(a.updated));$('#draftList').innerHTML=sorted.map(p=>`<div class="draft-row"><div class="draft-info"><b>${esc(p.data.name||'未命名项目')}${p.id===current.id?' · 当前':''}</b><small>${esc(label('types',p.data.types)||'未选类型')} · ${esc(new Date(p.updated).toLocaleDateString('zh-CN'))}</small></div><button class="btn" data-open-draft="${esc(p.id)}">打开</button><button class="btn subtle danger" data-delete-draft="${esc(p.id)}">删除</button></div>`).join('');if(!$('#draftDialog').open)$('#draftDialog').showModal()}
function choose(f,v){if(f.kind==='multi'){const values=current.data[f.id];const exclusive=['unsure','suggest','unknown'];if(values.includes(v))current.data[f.id]=values.filter(x=>x!==v);else if(exclusive.includes(v))current.data[f.id]=[v];else current.data[f.id]=[...values.filter(x=>!exclusive.includes(x)),v]}else current.data[f.id]=current.data[f.id]===v?'':v;errors=errors.filter(e=>e.id!==f.id);persist();render();$(`[data-choice="${f.id}"][data-value="${v}"]`)?.focus({preventScroll:true})}
// Preserve typing focus; only redraw the form when its structure changes.
document.addEventListener('input',e=>{const id=e.target.dataset.field;if(!id)return;current.data[id]=e.target.value;errors=errors.filter(x=>x.id!==id);const field=e.target.closest('.field');field.classList.remove('has-error');field.querySelector('.field-error')?.remove();e.target.removeAttribute('aria-invalid');persist();renderSteps()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.editField){navigate(Number(b.dataset.editStep));const target=$(`[data-group="${b.dataset.editField}"]`);target?.scrollIntoView({block:'center'});target?.querySelector('input,textarea,button')?.focus({preventScroll:true});return}
 if(b.dataset.choice){choose(fields.find(f=>f.id===b.dataset.choice),b.dataset.value);return}
 if(b.dataset.step!==undefined)return navigate(Number(b.dataset.step));if(b.hasAttribute('data-next'))return navigate(step+1);if(b.hasAttribute('data-prev'))return navigate(step-1);if(b.hasAttribute('data-result'))return navigate(4);
 if(b.id==='generateAgents')return generateAgents();if(b.id==='downloadAgents')return downloadAgents();if(b.id==='copyBrief')return copy();if(b.id==='exportMd')return download(brief(current.data),'md','text/markdown;charset=utf-8');if(b.id==='exportJson'||b.id==='backupDraft')return exportJSON();
 if(b.id==='newBtn'){if(storageError&&!confirm('当前草稿未能保存，仍要创建新项目吗？'))return;persist();current={id:uid(),updated:new Date().toISOString(),data:blank()};projects.push(current);persist();step=0;errors=[];render();toast('新项目已创建');return}
 if(b.id==='draftsBtn')return showDrafts();if(b.id==='closeDrafts')return $('#draftDialog').close();if(b.id==='importBtn'){$('#importFile').value='';$('#importFile').click();return}
 if(b.dataset.openDraft){persist();current=projects.find(p=>p.id===b.dataset.openDraft);step=0;errors=[];persist();$('#draftDialog').close();render();return}
 if(b.dataset.deleteDraft&&confirm('删除这份本机草稿？')){projects=projects.filter(p=>p.id!==b.dataset.deleteDraft);if(current.id===b.dataset.deleteDraft){current=projects[0]||{id:uid(),updated:new Date().toISOString(),data:blank()};if(!projects.length)projects.push(current);step=0;errors=[]}persist();render();showDrafts()}
});
$('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>500000)throw Error('文件超过 500 KB');const raw=JSON.parse(await file.text());if(raw.app!=='project-kickoff'||raw.version!==VERSION)throw Error('不是受支持的项目备份');const parsed=validProject({...raw.project,id:uid()});const data=parsed.data;current={id:parsed.id,updated:new Date().toISOString(),data,agents:parsed.agents};if(current.agents)generated.set(current.id,current.agents);projects.push(current);step=0;errors=[];persist();render();$('#draftDialog').close();toast('已导入为新草稿')}catch(err){toast(`导入失败：${err.message}`)}});
$('.brand').addEventListener('click',e=>{e.preventDefault();navigate(0)});
render();if(storageError)$('#saveStatus').textContent='保存不可用 · 请导出';
const context=document.modelContext;
if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'read_project_kickoff',title:'读取项目简报',description:'读取当前表单、必填缺口和协作建议；不修改状态或发送消息。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('不接受参数');return {brief:brief(current.data),missingRequired:validate(current.data).map(e=>e.id)}}})).catch(()=>{});}catch{}}

async function generateAgents(){
 if(generating)return;
 const projectId=current.id, input=brief(current.data);
 generating=true;renderResult();
 try{
  const r=await fetch('/api/generate-agents',{method:'POST',headers:{'Content-Type':'application/json','X-Kickoff-Request':'1'},body:JSON.stringify({brief:input})});
  let result;try{result=await r.json()}catch{throw Error('请通过本机启动服务使用模型生成，独立 HTML 不支持此功能')}
  if(!r.ok)throw Error(result.error||'生成失败');
  if(typeof result.markdown!=='string')throw Error('生成结果无效');
  const artifact={markdown:result.markdown,input};generated.set(projectId,artifact);const owner=projects.find(p=>p.id===projectId);if(owner){owner.agents=artifact;persist()}
  if(current.id===projectId&&step===4){renderResult();$('#agentsStatus').textContent=brief(current.data)===input?'已生成 · 草案可编辑，采用前核对待确认项':'已生成旧版输入的草案 · 表单已变化，请重新生成'}
  toast('AGENTS.md 已生成');
 }catch(e){if(current.id===projectId&&step===4)$('#agentsStatus').textContent=e.message;toast(e.message)}
 finally{generating=false;if($('#generateAgents')){$('#generateAgents').disabled=false;$('#generateAgents').textContent='生成 AGENTS.md'}}
}
function downloadAgents(){
 const item=generated.get(current.id);if(!item)return;
 if(item.input!==brief(current.data)){toast('表单已变化，请重新生成 AGENTS.md');return}
 const content=$('#agentsText').value;item.markdown=content;
 const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='AGENTS.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);
}
document.addEventListener('input',e=>{if(e.target.id==='agentsText'&&generated.has(current.id)){generated.get(current.id).markdown=e.target.value;current.agents=generated.get(current.id);persist()}});
